x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres

services:
  auas-db:
    <<: *postgres-common
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auas-master-data:/var/lib/postgresql/data
volumes:
  auas-master-data:
